name: HT
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10.13
  - numpy
  - matplotlib
  - prettytable
  - tqdm
  - pytest
  - ipython
  - jupyter
  - sphinx=5.3.0
  - pip
  - pip:
      - sphinx-rtd-theme
  - sphinxcontrib-bibtex=2.5.0
  - sphinx-copybutton
  - pydata-sphinx-theme
  - sphinx-autodoc-typehints=1.19.5
  - nbsphinx
  - jupytext
  - graphviz
  - pybtex
  - jupytext
  - pypandoc
  - pybtex
  - myst-parser
