name: docs_remote

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs_remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: ts-graphviz/setup-graphviz@v2
      - name: Install dependencies
        run: |
          pip install ".[docs]"
      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/build
      - name: Create CNAME
        run: |
          echo hofstadter.tools > docs/build/CNAME
      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'docs/build'
          destination-github-username: 'HofstadterTools'
          destination-repository-name: 'HTwebsite.github.io'
