name: pytests

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  pytests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: ts-graphviz/setup-graphviz@v1
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser pybtex sphinx-copybutton sphinxcontrib-bibtex sphinx-autodoc-typehints nbsphinx ipython pydata-sphinx-theme jupyter jupytext pypandoc numpy matplotlib prettytable tqdm pytest
      - name: Set the PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:code" >> "$GITHUB_ENV"
      - name: Run pytests
        run: |
          pytest code/tests/
